# # [START runtime]
# runtime: nodejs14
# env: standard
# service: onetruckpart
# # [END runtime]

# # [START handlers]
# handlers:
#   - url: /
#     static_files: build/index.html
#     upload: build/index.html
#   - url: /
#     static_dir: build
#   # [END handlers]


env: standard
runtime: nodejs14
# oneauto -- oneauto.us
# onetruckparts -- onetruckparts.com
service: oneauto
handlers:
  - url: /static
    secure: always
    static_dir: build/static
  - url: /(.*\.(json|ico|js))$
    secure: always
    redirect_http_response_code: 301
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
  - url: .*
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html
